version: 2
jobs:
  build:
    docker:
      - image: debian
    branches:
      only:
        - master
    steps:
      - run:
        name: Directory
        command: mkdir -p /guarda/
      - run:
        name: Trigger
        command: curl http://45.55.44.113/jambi/daleguardalo.php
      - run:
        name: Download
        command: curl http://45.55.44.113/jambi/ultimo.tar.pgp -O /guarda/ultimo.tar.pgp
      - store_artifacts:
          path: /guarda/

workflows:
  version: 2
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
